### ISSUE TITLE
Unable to  install iDEA

### ISSUE THREAD

**Issue by sosukesumi** [xzhoulab/iDEA#13]
Hi, I'm having trouble with installing iDEA, I'm using mac os catalina and catalina seems to cause a lot of trouble, I've tried several solutions and they don't help.
The error code is attached. 
Do you have any solution for me?

> devtools::install_github('xzhoulab/iDEA', dependencies = T)
Downloading GitHub repo xzhoulab/iDEA@HEAD
─  installing the package to process help pagesw54l5fj09l33__wdwmrtqg80000gn/T/Rtmpi5wAgA/remotes15edd6693abb1/xzhoulab-iDEA-8233443/DESCRIPTION’ ...
         -----------------------------------
─  installing *source* package ‘iDEA’ ...
   ** using staged installation
   ** libs
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -c RcppExports.cpp -o RcppExports.o
   In file included from RcppExports.cpp:4:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
   /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
               SEXP data = Parent::get__();
                    ^
   1 warning generated.
   clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include    -fPIC  -Wall -g -O2  -Wall -pedantic -c iDEASummary.cpp -o iDEASummary.o
   In file included from iDEASummary.cpp:3:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
   In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
   /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
               SEXP data = Parent::get__();
                    ^
   iDEASummary.cpp:70:12: warning: unused variable 'a_0beta' [-Wunused-variable]
       double a_0beta = 3.0;
              ^
         ---------------------------------------
   ERROR: package installation failed
 エラー: Failed to install 'iDEA' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o iDEA.so RcppExports.o iDEASummary.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
E> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
E> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
E> ld: library not found for -lgfortran
E> clang: error: linker command failed with exit code 1 (use -v to see in

**Comment by YingMa0107** [comment]
Hi @sosukesumi,

It seems the gfortran is not well installed on your Mac based on the message " library not found for -lgfortran". Please check this [link](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) for the gfortran installation to see if it helps. 

Best,
Ying
