### ISSUE TITLE
iDEA on n=1?

### ISSUE THREAD

**Issue by MardahlM** [xzhoulab/iDEA#19]
Dear authors, 

Your iDEA package seems very useful – I am keen to try it. 
I have created an integrated dataset using Seurat v4 from one control and one treatment single-cell RNA-seq sample from the public geodatabase. 
Does your package require more replicates (created by bootstrapping)? 

Cheers, Maibritt

**Comment by YingMa0107** [comment]
Hi @MardahlM,

Thank you for your interest in our package. Our package requires gene-level summary statistics in terms of fold change/effect size estimates and their standard errors, and gene sets (stored in iDEA) as inputs. So as long as you can get the summary statistics from Seurat, it can be used as the inputs. But the sample size (e.g. the number of cells, the more replicates you get, the large number of cells you will get) might have an influence on the differential expression analysis results, it might depend on the method. As most of the current public datasets are large-scale, I think the number of cells is enough for DE. 

Hope this helps. Let me know if you have further questions!

Best,
Ying
