### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by e-arslan** [xzhoulab/iDEA#2]
I'm trying to run the code provided in the tutorial and gets the following error:

idea <- iDEA.louis(idea)
Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 1 worker of 1 failed to connect.

I've tried to change the num_core but it didn't solve the problem.

**Comment by sqsun** [comment]
Please contact Ying Ma to address your question through email (yingma@umich.edu).
