### ISSUE TITLE
Output explanations

### ISSUE THREAD

**Issue by JRWallace** [xzhoulab/iDEA#24]
Hello! Thank you for this package. I am wondering if you have any details or information about how to interpret the outputs from `iDEA@gsea`. More specifically, what are the `annot_coef`, `annot_var`, `annot_var_louis`, and `sigma2_b`? This information is probably in the manuscript but I think it would be helpful to have it in the documentation for the package. 

 | annot_id<chr> | annot_coef<dbl> | annot_var<dbl> | annot_var_louis<dbl> | sigma2_b<dbl> | pvalue_louis<dbl> | pvalue<dbl>
-- | -- | -- | -- | -- | -- | -- | --
1 | REACTOME_FATTY_ACID_METABOLISM | -1.750754 | 0.09029776 | 0.1001064 | 238.8785 | 3.140330e-08 | 5.669802e-09
2 | REACTOME_GLYCOLYSIS | -1.135788 | 0.13735320 | 0.1483048 | 239.1861 | 3.184886e-03 | 2.179394e-03
3 | REACTOME_INTERFERON_SIGNALING | 1.775729 | 0.07376514 | 0.0796045 | 239.3457 | 3.099353e-10 | 6.230865e-11

Thanks,
Joselynn

**Comment by YingMa0107** [comment]
Hi @JRWallace, 

Thank you very much for your great suggestions. I have added some interpretations in the tutorial page. 

Specifically, the "annot_id" represents the gene set name, "annot_coef" is the estimated gene set enrichment parameter that determines the odds ratio of DE for genes inside the gene set versus genes outside the gene set. "annot_var" is the estimated variance of the annot_coef, "annot_var_louis" is the adjuested variance of the annot_coef by the Louis Method, "sigma2_b" is the scaling parameter. "pvalue_louis" is the pvalue calculated when applying Louis method to calibrate the pvalues while "pvalue" is the common pvalue without Louis Method correction. 

Thank you again! 

Best,
Ying
