### ISSUE TITLE
Change mouse gene names using BiomaRt

### ISSUE THREAD

**Issue by yuyingxie** [xzhoulab/iDEA#6]
I am running a mouse data sets for iDEA. The gene names in the mouseGeneSets are in the form of ‘MGI id’. How can I turn them into gene names like ‘Egfr’ and ‘Zzz3’? You mentioned to use biomaRt, but it is not clear to me how to do it. Can you help me with this issue

**Comment by YingMa1993** [comment]
Hi, 
Thank you for your interest in our package!
1. I use the first 10 MGIIDs in the mouse gene sets in our package as an example. 
####### Convert Mouse MGI ID to gene symbol using biomaRt package
library(biomaRt)
library(iDEA)
ensembl <- useMart("ensembl", dataset="mmusculus_gene_ensembl")
mouse_MGI_ids <- rownames(mouseGeneSets)[1:10]
GeneName <- getBM(attributes=c('ensembl_gene_id','external_gene_name','mgi_id'),
                                     filters = 'mgi_id',
                                     values = mouse_MGI_ids,
                                     mart = ensembl)
head(GeneName)
###### Here is the output
     ensembl_gene_id external_gene_name     mgi_id
1 ENSMUSG00000056201               Cfl1        MGI:101757
2 ENSMUSG00000035395             Dcaf8l      MGI:101758
3 ENSMUSG00000024261               Syt4       MGI:101759
4 ENSMUSG00000029439             Sfswap    MGI:101760
5 ENSMUSG00000056758              Hmga2   MGI:101761
6 ENSMUSG00000008398               Elk3      MGI:101762
######## Convert Mouse MGI ID to gene symbol on the website.
2. You can also paste your MGI IDs list to this website to get the detailed information of the genes.
http://www.informatics.jax.org/batch

Best,
Ying
