### ISSUE TITLE
Unable to install Package

### ISSUE THREAD

**Issue by zamlerd** [xzhoulab/iDEA#9]
Hello,

I was hoping to use your tool to analyze some scSeq datasets I generated-

On the install however I am getting this error-

─  installing *source* package ‘iDEA’ ...
   ** using staged installation
   ** libs
   clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
   clang: error: unsupported option '-fopenmp'
   make: *** [RcppExports.o] Error 1
   ERROR: compilation failed for package ‘iDEA’
─  removing ‘/private/var/folders/6n/zbwc61bx7_d3dpjbx4lkn_9ctqxgjh/T/RtmpoSxrNP/Rinst8e635314891/iDEA’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'iDEA' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> * installing *source* package ‘iDEA’ ...
E> ** using staged installation
E> ** libs
E> clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
E> clang: error: unsupported option '-fopenmp'
E> make: *** [RcppExports.o] Error 1
E> ERROR: compilation failed for package ‘iDEA’
E> * removing ‘/private/var/folders/6n/zbwc61bx7_d3dpjbx4lkn_9ctqxgjh/T/RtmpoSxrNP/Rinst8e635314891/iDEA’
E>       -----------------------------------
E> ERROR: package installation failed
In addition: Warning message:
replacing previous import ‘vctrs::data_frame’ by ‘tibble::data_frame’ when loading ‘dplyr’

Any idea why? I have already tried re-installing gcc through homebrew

Session info below
─ Session info ───────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Chicago             
 date     2020-10-13                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────
 package       * version  date       lib source        
 AnnotationDbi   1.48.0   2019-10-29 [1] Bioconductor  
 ape             5.4      2020-06-03 [1] CRAN (R 3.6.2)
 assertthat      0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 backports       1.1.8    2020-06-17 [1] CRAN (R 3.6.2)
 Biobase         2.46.0   2019-10-29 [1] Bioconductor  
 BiocGenerics    0.32.0   2019-10-29 [1] Bioconductor  
 BiocParallel    1.20.1   2019-12-21 [1] Bioconductor  
 bit             4.0.4    2020-08-04 [1] CRAN (R 3.6.2)
 bit64           4.0.5    2020-08-30 [1] CRAN (R 3.6.2)
 blob            1.2.1    2020-01-20 [1] CRAN (R 3.6.0)
 callr           3.4.3    2020-03-28 [1] CRAN (R 3.6.2)
 cli             2.0.2    2020-02-28 [1] CRAN (R 3.6.0)
 cluster         2.1.0    2019-06-19 [1] CRAN (R 3.6.1)
 codetools       0.2-16   2018-12-24 [1] CRAN (R 3.6.1)
 colorspace      1.4-1    2019-03-18 [1] CRAN (R 3.6.0)
 cowplot         1.0.0    2019-07-11 [1] CRAN (R 3.6.0)
 crayon          1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
 curl            4.3      2019-12-02 [1] CRAN (R 3.6.0)
 data.table      1.12.8   2019-12-09 [1] CRAN (R 3.6.0)
 DBI             1.1.0    2019-12-15 [1] CRAN (R 3.6.0)
 desc            1.2.0    2018-05-01 [1] CRAN (R 3.6.0)
 devtools        2.3.0    2020-04-10 [1] CRAN (R 3.6.2)
 digest          0.6.25   2020-02-23 [1] CRAN (R 3.6.0)
 DO.db           2.9      2020-05-05 [1] Bioconductor  
 DOSE          * 3.10.2   2019-06-24 [1] Bioconductor  
 dplyr           1.0.0    2020-05-29 [1] CRAN (R 3.6.2)
 ellipsis        0.3.1    2020-05-15 [1] CRAN (R 3.6.2)
 fansi           0.4.1    2020-01-08 [1] CRAN (R 3.6.0)
 fastmatch       1.1-0    2017-01-28 [1] CRAN (R 3.6.0)
 fgsea           1.10.1   2019-08-21 [1] Bioconductor  
 fitdistrplus    1.1-1    2020-05-19 [1] CRAN (R 3.6.2)
 fs              1.4.2    2020-06-30 [1] CRAN (R 3.6.2)
 future          1.18.0   2020-07-09 [1] CRAN (R 3.6.2)
 future.apply    1.6.0    2020-07-01 [1] CRAN (R 3.6.2)
 generics        0.0.2    2018-11-29 [1] CRAN (R 3.6.0)
 ggplot2         3.3.2    2020-06-19 [1] CRAN (R 3.6.2)
 ggrepel         0.8.2    2020-03-08 [1] CRAN (R 3.6.0)
 ggridges        0.5.2    2020-01-12 [1] CRAN (R 3.6.0)
 globals         0.12.5   2019-12-07 [1] CRAN (R 3.6.0)
 glue            1.4.2    2020-08-27 [1] CRAN (R 3.6.2)
 GO.db           3.8.2    2020-05-05 [1] Bioconductor  
 GOSemSim        2.10.0   2019-05-02 [1] Bioconductor  
 gridExtra       2.3      2017-09-09 [1] CRAN (R 3.6.0)
 gtable          0.3.0    2019-03-25 [1] CRAN (R 3.6.0)
 htmltools       0.5.0    2020-06-16 [1] CRAN (R 3.6.2)
 htmlwidgets     1.5.1    2019-10-08 [1] CRAN (R 3.6.0)
 httr            1.4.1    2019-08-05 [1] CRAN (R 3.6.0)
 ica             1.0-2    2018-05-24 [1] CRAN (R 3.6.0)
 igraph          1.2.5    2020-03-19 [1] CRAN (R 3.6.0)
 IRanges         2.20.2   2020-01-13 [1] Bioconductor  
 irlba           2.3.3    2019-02-05 [1] CRAN (R 3.6.0)
 jsonlite        1.7.0    2020-06-25 [1] CRAN (R 3.6.2)
 KernSmooth      2.23-17  2020-04-26 [1] CRAN (R 3.6.2)
 lattice         0.20-41  2020-04-02 [1] CRAN (R 3.6.2)
 lazyeval        0.2.2    2019-03-15 [1] CRAN (R 3.6.0)
 leiden          0.3.3    2020-02-04 [1] CRAN (R 3.6.0)
 lifecycle       0.2.0    2020-03-06 [1] CRAN (R 3.6.0)
 listenv         0.8.0    2019-12-05 [1] CRAN (R 3.6.0)
 lmtest          0.9-37   2019-04-30 [1] CRAN (R 3.6.0)
 magrittr        1.5      2014-11-22 [1] CRAN (R 3.6.0)
 MASS            7.3-51.6 2020-04-26 [1] CRAN (R 3.6.2)
 Matrix          1.2-18   2019-11-27 [1] CRAN (R 3.6.0)
 memoise         1.1.0    2017-04-21 [1] CRAN (R 3.6.0)
 munsell         0.5.0    2018-06-12 [1] CRAN (R 3.6.0)
 nlme            3.1-148  2020-05-24 [1] CRAN (R 3.6.2)
 patchwork       1.0.1    2020-06-22 [1] CRAN (R 3.6.2)
 pbapply         1.4-2    2019-08-31 [1] CRAN (R 3.6.0)
 pillar          1.4.6    2020-07-10 [1] CRAN (R 3.6.2)
 pkgbuild        1.1.0    2020-07-13 [1] CRAN (R 3.6.1)
 pkgconfig       2.0.3    2019-09-22 [1] CRAN (R 3.6.0)
 pkgload         1.1.0    2020-05-29 [1] CRAN (R 3.6.2)
 plotly          4.9.2.1  2020-04-04 [1] CRAN (R 3.6.2)
 plyr            1.8.6    2020-03-03 [1] CRAN (R 3.6.1)
 png             0.1-7    2013-12-03 [1] CRAN (R 3.6.0)
 prettyunits     1.1.1    2020-01-24 [1] CRAN (R 3.6.0)
 processx        3.4.3    2020-07-05 [1] CRAN (R 3.6.2)
 ps              1.3.3    2020-05-08 [1] CRAN (R 3.6.2)
 purrr           0.3.4    2020-04-17 [1] CRAN (R 3.6.2)
 qvalue          2.16.0   2019-05-02 [1] Bioconductor  
 R6              2.4.1    2019-11-12 [1] CRAN (R 3.6.0)
 RANN            2.6.1    2019-01-08 [1] CRAN (R 3.6.0)
 RColorBrewer    1.1-2    2014-12-07 [1] CRAN (R 3.6.0)
 Rcpp            1.0.5    2020-07-06 [1] CRAN (R 3.6.2)
 RcppAnnoy       0.0.16   2020-03-08 [1] CRAN (R 3.6.0)
 remotes         2.1.1    2020-02-15 [1] CRAN (R 3.6.0)
 reshape2        1.4.4    2020-04-09 [1] CRAN (R 3.6.2)
 reticulate      1.16     2020-05-27 [1] CRAN (R 3.6.2)
 rlang           0.4.7    2020-07-09 [1] CRAN (R 3.6.2)
 ROCR            1.0-11   2020-05-02 [1] CRAN (R 3.6.2)
 rprojroot       1.3-2    2018-01-03 [1] CRAN (R 3.6.0)
 RSQLite         2.2.0    2020-01-07 [1] CRAN (R 3.6.0)
 rstudioapi      0.11     2020-02-07 [1] CRAN (R 3.6.0)
 rsvd            1.0.3    2020-02-17 [1] CRAN (R 3.6.0)
 Rtsne           0.15     2018-11-10 [1] CRAN (R 3.6.0)
 S4Vectors       0.24.4   2020-04-09 [1] Bioconductor  
 scales          1.1.1    2020-05-11 [1] CRAN (R 3.6.2)
 sctransform     0.2.1    2019-12-17 [1] CRAN (R 3.6.0)
 sessioninfo     1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 Seurat          3.1.5    2020-04-16 [1] CRAN (R 3.6.2)
 stringi         1.4.6    2020-02-17 [1] CRAN (R 3.6.0)
 stringr         1.4.0    2019-02-10 [1] CRAN (R 3.6.0)
 survival        3.2-3    2020-06-13 [1] CRAN (R 3.6.2)
 testthat        2.3.2    2020-03-02 [1] CRAN (R 3.6.1)
 tibble          3.0.3    2020-07-10 [1] CRAN (R 3.6.2)
 tidyr           1.1.0    2020-05-20 [1] CRAN (R 3.6.2)
 tidyselect      1.1.0    2020-05-11 [1] CRAN (R 3.6.2)
 tsne            0.1-3    2016-07-15 [1] CRAN (R 3.6.0)
 usethis         1.6.1    2020-04-29 [1] CRAN (R 3.6.2)
 uwot            0.1.8    2020-03-16 [1] CRAN (R 3.6.0)
 vctrs           0.3.4    2020-08-29 [1] CRAN (R 3.6.2)
 viridisLite     0.3.0    2018-02-01 [1] CRAN (R 3.6.0)
 withr           2.2.0    2020-04-20 [1] CRAN (R 3.6.2)
 zoo             1.8-8    2020-05-02 [1] CRAN (R 3.6.2)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

**Comment by YingMa1993** [comment]
Hi @zamlerd 

Based on your error, I guess that the installed compiler on your MAC does not support OpenMP. So you have to install the compile which supports the OpenMP. I recommend you to install the compilers such as gcc or clang from homebrew, and after install them, you have to modify variables in your personal makeovers file (~/.R/Makevars). Here is an example of the ~/.R/Makevars files when using gcc as the compiler on the macOS. 

VER=-11.0.3
CC=gcc$(VER)
CXX=g++$(VER)
CFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion
CXXFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion
FLIBS=-L/usr/local/Cellar/gcc/11.0.3/lib/gcc/11

The first line is the gcc version on your computer (type gcc --version on your terminal, you will got the information).And you also have to modify the last line according to your version of gcc.

You can use the homebrew to install it, i.e. brew install gcc

If this does not help, here are also other solutions you can follow: https://github.com/RcppCore/RcppArmadillo/issues/143 

Hope it helps!

Best,
Ying

**Comment by zamlerd** [comment]
Hey Ying,

After trying both methods above I am now getting a new error

devtools::install_github('xzhoulab/iDEA')
Registered S3 method overwritten by 'cli':
  method     from    
  print.boxx spatstat
Downloading GitHub repo xzhoulab/iDEA@HEAD
Error: Failed to install 'iDEA' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

I have devtools installed and can call it

**Comment by YingMa1993** [comment]
Hi @zamlerd,

Could you please call the function pkgbuild::check_build_tools(debug = TRUE) to see the output? 
For example, this is the output of mine: 

pkgbuild::check_build_tools(debug = TRUE)
Trying to compile a simple C file
\Running /usr/lib/R/bin/R CMD SHLIB foo.c
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -O3 -pipe  -g  -c foo.c -o foo.o
gcc -std=gnu99 -shared -o foo.so foo.o -L/usr/lib/R/lib -lR
 
Your system is ready to build packages!

Just want to check if you have installed the tools necessary to compile the package. 

Thanks!
